apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/
components:
  - ../components/pull-secret
patches:
  - target:
      kind: Deployment
    path: 'nfs.patch.yaml'
